[project]
name = "mlx-model-training-evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.1.0",
    "ipykernel>=7.4.0",
    "jsonschema>=4.26.0",
    "jupyterlab>=4.6.4",
    "matplotlib>=3.11.2",
    "mlx>=0.32.3",
    "mlx-lm>=0.32.0",
    "pydantic>=2.13.5",
    "rich>=15.0.0",
    "tabulate>=0.10.0",
    "tqdm>=4.70.1",
]
